seed: 1
model: 'SPACE'
resume: true
resume_ckpt: ''
parallel: false
device_ids: [0]
device: 'cuda:0'
logdir: '../output/logs'
checkpointdir: '../output/checkpoints'
evaldir: '../output/eval/'

dataset: 'MNIST'
dataset_roots:
  MNIST: '../data'


# For engine.train
train:
  batch_size: 16
  max_epochs: 1000
  max_steps: 160000
  print_every: 500
  save_every: 1000
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: false
  solver:
    fg:
      optim: 'RMSprop'
      lr: 1e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

# For package model
arch:
  G: 16
  fg_sigma: 0.15

  z_pres_start_step: 10000
  z_pres_end_step: 15000
  z_pres_start_value: 0.1
  z_pres_end_value: 1e-10

  z_scale_mean_start_step: 0
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -2.0
  z_scale_mean_end_value: -2.5

  tau_start_step: 0
  tau_end_step: 10000
  tau_start_value: 2.5
  tau_end_value: 2.5

  fix_alpha_steps: 4000
  fix_alpha_value: 0.1

  K: 3
  bg_sigma: 0.10
  boundary_loss: false
